import type { WarehouseSnapshot } from "@twinops/shared";

const time = "2026-07-18T08:00:00.000Z";

/**
 * A deliberately small but fully linked snapshot for cross-workspace navigation
 * tests. Product views may add fields over time; navigation only relies on the
 * identifiers and relationships represented here.
 */
export function makeNavigationSnapshot(): WarehouseSnapshot {
  return {
    zones: [],
    inventoryPlacements: [],
    shipments: [],
    docks: [
      { id: "D-01", name: "Dock 1", status: "occupied", currentShipmentId: null, nextAvailableAt: time },
      { id: "D-02", name: "Dock 2", status: "occupied", currentShipmentId: "SHIP-OUT", nextAvailableAt: time }
    ],
    dockSchedule: [],
    routes: [
      {
        routeId: "ROUTE-IN",
        id: "LEGACY-ROUTE-IN",
        direction: "inbound",
        transportLegId: "LEG-IN",
        asnId: "ASN-IN",
        shipmentId: null,
        dockAppointmentId: "APPT-IN"
      },
      {
        routeId: "ROUTE-OUT",
        id: "LEGACY-ROUTE-OUT",
        direction: "outbound",
        transportLegId: "LEG-OUT",
        asnId: null,
        shipmentId: "SHIP-OUT",
        dockAppointmentId: "APPT-OUT"
      }
    ],
    temperatureReadings: [],
    temperatureEvents: [],
    rfidEvents: [],
    alerts: [],
    decisions: [],
    operationalIssues: [],
    partnerSites: [
      {
        siteId: "WAREHOUSE",
        partnerId: "WAREHOUSE",
        partnerName: "Western Distribution Centre",
        siteCode: "WAREHOUSE",
        role: "warehouse",
        displayName: "Western Distribution Centre",
        address: "Singapore",
        postalCode: "000000",
        countryCode: "SG",
        timezone: "Asia/Singapore",
        location: { lat: 1.33, lng: 103.74 },
        receivingWindow: "24 hours",
        temperatureCapabilities: ["ambient", "2-8C", "15-25C"],
        vehicleRestrictions: [],
        simulated: true,
        publicLocationReference: null,
        dataNotice: "Synthetic test site"
      },
      {
        siteId: "SUPPLIER",
        partnerId: "SUPPLIER",
        partnerName: "Supplier",
        siteCode: "SUPPLIER",
        role: "supplier",
        displayName: "Supplier",
        address: "Singapore",
        postalCode: "000001",
        countryCode: "SG",
        timezone: "Asia/Singapore",
        location: { lat: 1.35, lng: 103.8 },
        receivingWindow: "08:00-18:00",
        temperatureCapabilities: ["2-8C"],
        vehicleRestrictions: [],
        simulated: true,
        publicLocationReference: null,
        dataNotice: "Synthetic test site"
      },
      {
        siteId: "CUSTOMER",
        partnerId: "CUSTOMER",
        partnerName: "Customer",
        siteCode: "CUSTOMER",
        role: "customer",
        displayName: "Customer",
        address: "Singapore",
        postalCode: "000002",
        countryCode: "SG",
        timezone: "Asia/Singapore",
        location: { lat: 1.3, lng: 103.84 },
        receivingWindow: "08:00-18:00",
        temperatureCapabilities: ["ambient"],
        vehicleRestrictions: [],
        simulated: true,
        publicLocationReference: null,
        dataNotice: "Synthetic test site"
      }
    ],
    transportLegs: [
      {
        transportLegId: "LEG-IN",
        routeId: "ROUTE-IN",
        direction: "inbound",
        asnId: "ASN-IN",
        shipmentId: null,
        dockAppointmentId: "APPT-IN",
        temperatureRequirement: "2-8C",
        routeStatus: "on-time",
        originSiteId: "SUPPLIER",
        destinationSiteId: "WAREHOUSE",
        carrierId: "CARRIER-IN",
        carrierName: "Inbound Carrier",
        vehicleId: "VEHICLE-IN",
        vehicleType: "Refrigerated truck",
        licensePlate: "SG-IN-01",
        driverId: null,
        plannedDeparture: time,
        actualDeparture: null,
        plannedArrival: "2026-07-18T09:00:00.000Z",
        actualArrival: null,
        estimatedArrival: "2026-07-18T09:00:00.000Z",
        deliveryWindowStart: null,
        deliveryWindowEnd: null,
        temperatureMin: 2,
        temperatureMax: 8,
        temperatureStatus: "compliant",
        temperatureLoggerId: "LOGGER-IN",
        transportStatus: "planned",
        distanceKm: 10,
        baseDurationMinutes: 30,
        durationMinutes: 30,
        delayMinutes: 0,
        disruptionType: null,
        riskLevel: "low",
        riskNote: "No known risk",
        receivingImpact: "On schedule",
        mitigationSuggestion: "Monitor",
        encodedPolyline: null,
        polyline: [{ lat: 1.35, lng: 103.8 }, { lat: 1.33, lng: 103.74 }],
        lastKnownLocation: { lat: 1.35, lng: 103.8 },
        lastComputedAt: time,
        cacheSource: "fallback",
        providerUsed: "fallback",
        isRealRoadRoute: true,
        sealNumber: "SEAL-IN",
        proofOfDeliveryId: null,
        lastUpdatedAt: time
      },
      {
        transportLegId: "LEG-OUT",
        routeId: "ROUTE-OUT",
        direction: "outbound",
        asnId: null,
        shipmentId: "SHIP-OUT",
        dockAppointmentId: "APPT-OUT",
        temperatureRequirement: "ambient",
        routeStatus: "on-time",
        originSiteId: "WAREHOUSE",
        destinationSiteId: "CUSTOMER",
        carrierId: "CARRIER-OUT",
        carrierName: "Outbound Carrier",
        vehicleId: "VEHICLE-OUT",
        vehicleType: "Box truck",
        licensePlate: "SG-OUT-02",
        driverId: null,
        plannedDeparture: time,
        actualDeparture: null,
        plannedArrival: "2026-07-18T10:00:00.000Z",
        actualArrival: null,
        estimatedArrival: "2026-07-18T10:00:00.000Z",
        deliveryWindowStart: time,
        deliveryWindowEnd: "2026-07-18T11:00:00.000Z",
        temperatureMin: null,
        temperatureMax: null,
        temperatureStatus: "not_required",
        temperatureLoggerId: null,
        transportStatus: "planned",
        distanceKm: 12,
        baseDurationMinutes: 35,
        durationMinutes: 35,
        delayMinutes: 0,
        disruptionType: null,
        riskLevel: "low",
        riskNote: "No known risk",
        receivingImpact: "On schedule",
        mitigationSuggestion: "Monitor",
        encodedPolyline: null,
        polyline: [{ lat: 1.33, lng: 103.74 }, { lat: 1.3, lng: 103.84 }],
        lastKnownLocation: { lat: 1.33, lng: 103.74 },
        lastComputedAt: time,
        cacheSource: "fallback",
        providerUsed: "fallback",
        isRealRoadRoute: true,
        sealNumber: "SEAL-OUT",
        proofOfDeliveryId: null,
        lastUpdatedAt: time
      }
    ],
    dockAppointments: [
      {
        dockAppointmentId: "APPT-IN",
        dockId: "D-01",
        direction: "inbound",
        transportLegId: "LEG-IN",
        referenceType: "ASN",
        referenceId: "ASN-IN",
        scheduledStart: "2026-07-18T08:00:00.000Z",
        scheduledEnd: "2026-07-18T09:00:00.000Z",
        actualGateIn: null,
        actualDockIn: null,
        actualDockOut: null,
        actualGateOut: null,
        status: "booked",
        carrierId: "CARRIER-IN",
        carrierName: "Inbound Carrier",
        vehicleId: "VEHICLE-IN",
        licensePlate: "SG-IN-01",
        temperatureRequirement: "2-8C",
        conflictFlag: false,
        notes: "Synthetic inbound appointment",
        lastUpdatedAt: time
      },
      {
        dockAppointmentId: "APPT-OUT",
        dockId: "D-02",
        direction: "outbound",
        transportLegId: "LEG-OUT",
        referenceType: "Outbound Shipment",
        referenceId: "SHIP-OUT",
        scheduledStart: "2026-07-18T09:00:00.000Z",
        scheduledEnd: "2026-07-18T10:00:00.000Z",
        actualGateIn: null,
        actualDockIn: null,
        actualDockOut: null,
        actualGateOut: null,
        status: "booked",
        carrierId: "CARRIER-OUT",
        carrierName: "Outbound Carrier",
        vehicleId: "VEHICLE-OUT",
        licensePlate: "SG-OUT-02",
        temperatureRequirement: "ambient",
        conflictFlag: false,
        notes: "Synthetic outbound appointment",
        lastUpdatedAt: time
      }
    ],
    operationalEvents: [],
    logistics: {
      warehouseSiteId: "WAREHOUSE",
      simulationDisclosure: "Synthetic test fixture",
      partnerSites: [],
      transportLegs: [],
      dockAppointments: [],
      operationalEvents: []
    },
    inventory: {
      products: [],
      batches: [],
      locations: [],
      stockBalances: [],
      inboundShipments: [
        {
          asnId: "ASN-IN",
          linkedRouteId: "ROUTE-IN",
          transportLegId: "LEG-IN",
          dockAppointmentId: "APPT-IN",
          receivingDock: "D-01",
          source: "Supplier",
          routeName: "Inbound route",
          eta: time,
          inboundStatus: "Scheduled",
          coldChainStatus: "compliant",
          purchaseOrderId: "PO-IN",
          supplierSiteId: "SUPPLIER",
          plannedArrival: time,
          actualArrival: null,
          goodsReceiptNumber: null,
          vehicleId: "VEHICLE-IN",
          sealNumber: "SEAL-IN"
        }
      ],
      inboundLines: [],
      outboundShipments: [
        {
          shipmentId: "SHIP-OUT",
          routeId: "ROUTE-OUT",
          transportLegId: "LEG-OUT",
          dockAppointmentId: "APPT-OUT",
          dock: "D-02",
          destination: "Customer",
          requiredBy: time,
          outboundStatus: "Scheduled",
          priorityLevel: "Normal",
          customerOrderId: "ORDER-OUT",
          deliveryId: "DELIVERY-OUT",
          customerSiteId: "CUSTOMER",
          plannedDeparture: time,
          actualDeparture: null,
          deliveryWindowStart: time,
          deliveryWindowEnd: "2026-07-18T11:00:00.000Z",
          goodsIssueNumber: null,
          proofOfDeliveryId: null,
          vehicleId: "VEHICLE-OUT",
          sealNumber: "SEAL-OUT"
        }
      ],
      outboundLines: [],
      movements: [],
      stockPositions: [],
      summary: {
        onHand: 0,
        available: 0,
        reserved: 0,
        incomingToday: 0,
        outboundToday: 0,
        qaHold: 0,
        productCount: 0,
        batchCount: 0
      }
    },
    kpis: {
      fefoCompliance: 100,
      coldChainIntegrity: 100,
      dockUtilisation: 50,
      activeShipments: 2,
      stockBalancesAtExpiryRisk: 0,
      assistantEnquiries: 0
    }
  } as unknown as WarehouseSnapshot;
}
